# Example application-specific west.yml, using manifest imports.
manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      remote: nrfconnect
      revision: 4b012fb4882f0ddd3de9f339ebc5a3f1c3cacd4a
      import: true
  self:
    # This repository should be cloned to ncs/nrf.
    path: pyrinas