# Example application-specific west.yml, using manifest imports.
manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: nanopb
      url-base: https://github.com/nanopb
  projects:
    - name: nrf
      remote: nrfconnect
      revision: bce1d6bc5b3b34587aaeeccc2fc377c534935364
      import: true
    - name: nanopb
      repo-path: nanopb
      revision: 0.3.9
      path: pyrinas/ext/nanopb
      remote: nanopb
  self:
    # This repository should be cloned to ncs/nrf.
    path: pyrinas