# Pryinas west.yml
manifest:
  projects:
    - name: qcbor
      url: https://github.com/jaredwolff/QCBOR.git
      revision: dev
      path: modules/lib/qcbor
    - name: pyrinas-codec
      url: https://github.com/pyrinas-iot/pyrinas-codec.git
      revision: master
      path: modules/lib/pyrinas/ext/pyrinas-codec
  self:
    path: modules/lib/pyrinas

